(deftheme spacemacs-dark-fix
  "Created 2019-06-22.")

(custom-theme-set-variables
 'spacemacs-dark-fix
 '(ansi-color-names-vector ["#0a0814" "#f2241f" "#67b11d" "#b1951d" "#4f97d7" "#a31db1" "#28def0" "#b2b2b2"])
 '(hl-todo-keyword-faces (quote (("TODO" . "#dc752f") ("NEXT" . "#dc752f") ("THEM" . "#2d9574") ("PROG" . "#4f97d7") ("OKAY" . "#4f97d7") ("DONT" . "#f2241f") ("FAIL" . "#f2241f") ("DONE" . "#86dc2f") ("NOTE" . "#b1951d") ("KLUDGE" . "#b1951d") ("HACK" . "#b1951d") ("TEMP" . "#b1951d") ("FIXME" . "#dc752f") ("XXX" . "#dc752f") ("XXXX" . "#dc752f") ("???" . "#dc752f")))))

(custom-theme-set-faces
 'spacemacs-dark-fix
 '(cursor ((((class color) (min-colors 89)) (:background "#e3dedd"))))
 '(custom-button ((((class color) (min-colors 89)) :background "#212026" :foreground "#b2b2b2" :box (:line-width 2 :style released-button))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(eval-sexp-fu-flash ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "#292b2e"))))
 '(eval-sexp-fu-flash-error ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#292b2e"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :background "#292e34" :slant normal))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#9f8766"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7" :slant normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2d9574"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#ce537a" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#292b2e"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2"))))
 '(header-line ((((class color) (min-colors 89)) :background "#0a0814")))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444155"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#212026"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#86dc2f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#29422d" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#2aa1ae" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#444155" :foreground "#86dc2f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7"))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(region ((((class color) (min-colors 89)) (:background "#444155"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#100a14"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#686868"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#5d4d7a"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(ahs-face ((((class color) (min-colors 89)) (:background "#444155"))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "#292b2e"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#b1951d" :inherit bold))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "#292b2e"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#b2b2b2"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#212026"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#5d4d7a"))))
 '(company-template-field ((((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#ce537a"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#4f97d7"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2"))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#4f97d7")))
 '(diff-header ((((class color) (min-colors 89)) :background "#373040" :foreground "#bc6ec5")))
 '(diff-file-header ((((class color) (min-colors 89)) :background "#373040" :foreground "#cbc1d5")))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#4f97d7")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#292b2e")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#4f97d7" :foreground "#292b2e")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#f2241f" :foreground "#292b2e")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#f2241f")))
 '(diff-hl-change ((((class color) (min-colors 89)) :background "#2d4252" :foreground "#4f97d7")))
 '(diff-hl-delete ((((class color) (min-colors 89)) :background "#512e31" :foreground "#f2241f")))
 '(diff-hl-insert ((((class color) (min-colors 89)) :background "#29422d" :foreground "#67b11d")))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#a31db1" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 89)) (:background "#3c2a2c" :foreground "#f2241f"))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 89)) (:background "#293235" :foreground "#67b11d"))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flymake-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flymake-note ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(flymake-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(flyspell-duplicate ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style wave :color "#4f97d7"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#4f97d7" :inherit bold :underline t))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:background "#dc752f" :foreground "#292b2e"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#4f97d7" :inherit bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#292b2e" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#86dc2f" :background "#292b2e" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#292b2e" :inherit bold))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "#292b2e" :background "#4f97d7" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#292b2e" :inherit bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#ce537a" :background "#292b2e" :inherit bold))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background nil))))
 '(helm-match ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7"))))
 '(helm-match-item ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#7590db" :background "#292b2e"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#444155"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#212026"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#c56ec3" :background "#292b2e"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#c56ec3" :foreground "#292b2e" :inherit bold))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#100a14"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#c56ec3" :inherit bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(ido-vertical-match-face ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline nil))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :underline t))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#44505c" :background "#212026" :inherit default))))
 '(line-number ((((class color) (min-colors 89)) (:foreground "#44505c" :background "#212026" :inherit default))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#212026" :inherit line-number))))
 '(magit-blame-date ((((class color) (min-colors 89)) :background "#32322c" :foreground "#67b11d")))
 '(magit-blame-hash ((((class color) (min-colors 89)) :background "#32322c" :foreground "#bc6ec5")))
 '(magit-blame-heading ((((class color) (min-colors 89)) :background "#32322c" :foreground "#67b11d")))
 '(magit-blame-name ((((class color) (min-colors 89)) :background "#32322c" :foreground "#b1951d")))
 '(magit-blame-summary ((((class color) (min-colors 89)) :background "#32322c" :foreground "#b1951d")))
 '(magit-branch-current ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7" :inherit bold :box t))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:background "#293239" :foreground "#4f97d7" :inherit bold))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:background "#293235" :foreground "#2d9574" :inherit bold))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#5e5079" :foreground "#b2b2b2"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#7590db"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#a31db1"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#a31db1"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#28def0"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:foreground "#f2241f"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#4f97d7" :inherit bold))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#212026"))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit bold :foreground "#4f97d7" :height 1.3 :background nil))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit bold :foreground "#2d9574" :height 1.2 :background nil))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b1951d" :background nil))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#4f97d7"))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2d9574"))))
 '(markdown-table-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#293239"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#222226" :box (:color "#5d4d7a" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#bc6ec5"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e" :box (:color "#5d4d7a" :line-width 1)))))
 '(org-kbd ((((class color) (min-colors 89)) (:inherit region :foreground "#b2b2b2" :box (:line-width 1 :style released-button)))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#5d4d7a" :foreground "#b2b2b2"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#212026" :foreground "#b2b2b2"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "#67b11d")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "#b1951d")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "#bc6ec5")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "#2d9574")))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :underline t))))
 '(show-paren-match-expression ((((class color) (min-colors 89)) (:background "#29422d"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold :underline t))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#444155" :foreground nil))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :underline t))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#32322c"))))
 '(smerge-markers ((((class color) (min-colors 89)) (:background "#34323e" :foreground "#9a9aba"))))
 '(smerge-upper ((((class color) (min-colors 89)) (:background "#3c2a2c"))))
 '(smerge-lower ((((class color) (min-colors 89)) (:background "#293235"))))
 '(smerge-refined-added ((((class color) (min-colors 89)) (:background "#29422d" :foreground "#67b11d"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#2d4252" :foreground "#4f97d7"))))
 '(smerge-refined-removed ((((class color) (min-colors 89)) (:background "#512e31" :foreground "#f2241f"))))
 '(spaceline-flycheck-error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(spaceline-flycheck-info ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(spaceline-flycheck-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(spaceline-python-venv ((((class color) (min-colors 89)) (:foreground "#c56ec3"))))
 '(spacemacs-transient-state-title-face ((((class color) (min-colors 89)) (:background nil :foreground "#c56ec3" :box nil :inherit bold))))
 '(term ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#292b2e"))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#0a0814" :background "#0a0814"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "#4f97d7" :background "#4f97d7"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#28def0" :background "#28def0"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "#67b11d" :background "#67b11d"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#a31db1" :background "#a31db1"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#f2241f" :background "#f2241f"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#b2b2b2"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#b1951d" :background "#b1951d"))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#4f97d7"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#bc6ec5" :inherit bold))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:background nil :foreground "#2d9574"))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:background "#bc6ec5" :foreground "#292b2e"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#bc6ec5"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#c56ec3" :underline nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#4f97d7")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#b2b2b2")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#c56ec3")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#7590db")))
 '(default ((((class color) (min-colors 89)) (:background "#292b2e" :foreground "#b2b2b2")))))

(provide-theme 'spacemacs-dark-fix)
